export enum DataTests {
  protocol_dropdown_trigger = 'protocol_dropdown_trigger',
  protocol_dropdown_menu_content = 'protocol_dropdown_menu_content',
  protocol_dropdown_menu_item = 'protocol_dropdown_menu_item',
  transaction_decoder_title = 'transaction_decoder_title',
  transaction_decoder_subtitle = 'transaction_decoder_subtitle',
  transaction_decoder_info_trigger = 'transaction_decoder_info_trigger',
  transaction_decoder_textarea = 'transaction_decoder_textarea',
  transaction_decoder_transaction_hash = 'transaction_decoder_transaction_hash',
  transaction_decoder_tab_content = 'transaction_decoder_tab_content',
  transaction_decoder_empty_state = 'transaction_decoder_empty_state',
  transaction_decoder_run_button = 'transaction_decoder_run_button',
  transaction_decoder_tab_summary_trigger = 'transaction_decoder_tab_summary_trigger',
  transaction_decoder_tab_json_trigger = 'transaction_decoder_tab_json_trigger',
}
